/**
 * Información general de la base de datos
 */
export const generalInfo = `
-- ============================================================
-- Airline Reservation System Schema
-- Author: Generated by ChatGPT (OpenAI o3)
-- Date: 2025-05-26 13:00:25
-- ============================================================

CREATE DATABASE IF NOT EXISTS airline_reservation
  DEFAULT CHARACTER SET utf8mb4
  COLLATE utf8mb4_unicode_ci;
USE airline_reservation;`;
